rng_seed: ${rng_seed}
n_jobs_study: 1
n_jobs_cv: -1
n_jobs_final_model: -1
target_col_modeling: w_total_median_profit
year_col: year
train_range: [2010, 2014]
val_range: [2015, 2015]
test_range: [2016, 2017]

experiment_prefix: rf_optuna_trial
experiment_id: "${.experiment_prefix}_${now:%Y-%m-%d_%H-%M-%S}"

artifact_directory_path: "artifacts"

permutation_importances_filename: "permutation_importances.csv"
randomforest_importances_filename: "randomforest_importances.csv"

top_n_importances: 10
optuna_n_trials: 5
cv_splits: 4
direction: minimize

scoring:
  rmse: neg_root_mean_squared_error
  r2: r2

mlflow_tags:
  run_id_tag: ${run_id_outputs}
  data_version_tag: ${data_versions.data_version_input}
