default_stages: [commit, push]

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks: [{id: black, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks: [{id: isort, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.277
    hooks: [{id: ruff, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [pydantic]
        exclude: ^(notebooks|trouble|src|bin/backup_repo)/
