default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks: [{id: black, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks: [{id: isort, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.6
    hooks: [{id: ruff, exclude: ^(notebooks|trouble|src|bin/backup_repo)/}]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic]
        exclude: ^(notebooks|trouble|src|bin/backup_repo)/
