# configs/logging_utils/base.yaml
log_directory_path: "${paths.directories.logs}/pipeline"
log_file_path: "${.log_directory_path}/${now:%Y-%m-%d_%H-%M-%S}.log"
formatter: "%(asctime)s %(levelname)s:%(message)s"
level: 20

log_cfg_job:
  log_for_each_step: false
  output_cfg_job_directory_path: ${hydra.run.dir}
  output_cfg_job_file_path: ${hydra.run.dir}/cfg_job_${hydra.job.name}.yaml
  resolve: true
