csv_to_dataframe:
  file_path: ${data_storage.input_file_path}
  low_memory: false

dataframe_to_csv:
  output_file_path: ${data_storage.output_file_path}
  include_index: false

calculate_and_save_metadata:
  data_file_path: ${data_storage.output_file_path}
  output_metadata_file_path: ${data_storage.output_metadata_file_path}
