# File paths input data
input_file_path_csv: ${paths.directories.data}/${data_versions.data_version_input}/${data_versions.data_version_input}.csv
input_file_path_json: ${paths.directories.data}/${data_versions.data_version_input}/${data_versions.data_version_input}.json
input_metadata_file_path: ${paths.directories.data}/${data_versions.data_version_input}/${data_versions.data_version_input}_metadata.json

# File paths output data
output_file_path_csv: ${paths.directories.data}/${data_versions.data_version_output}/${data_versions.data_version_output}.csv
output_file_path_json: ${paths.directories.data}/${data_versions.data_version_output}/${data_versions.data_version_output}.json
output_metadata_file_path: ${paths.directories.data}/${data_versions.data_version_output}/${data_versions.data_version_output}_metadata.json

# File path outputs by run_id_outputs
run_id_outputs_directory_path: ${paths.directories.outputs}/${setup.script_base_name}/${run_id_outputs}
