file_type: csv
input_file_extension: .${.file_type}
output_file_extension: ${.input_file_extension}
input_metadata_file_extension: .json
output_metadata_file_extension: ${.input_metadata_file_extension}
train: false
test: false
single_file: true

# File path outputs by run_id_outputs
run_id_outputs_directory_path: ${paths.directories.outputs}/${setup.script_base_name}/${run_id_outputs}
