defaults:
  - base
  - _self_

lag_columns:
  columns_to_transform:
    - sum_discharges
    - severity_1_portion
    - severity_2_portion
    - severity_3_portion
    - severity_4_portion
    - w_mean_charge
    - w_mean_cost
    - w_mean_profit
    - w_total_mean_profit
    - w_total_mean_cost
    - w_median_charge
    - w_median_cost
    - w_median_profit
    - w_total_median_profit
    - w_total_median_cost
  groupby_time_based_cols: [facility_id, apr_drg_code, year]
  drop: true
  groupby_lag_cols: [facility_id, apr_drg_code]
  lag1_suffix: _lag1
  shift_periods: 1
