# configs/transformations/rf_optuna_trial.yaml
defaults:
  - base
  - /model_params: rf_optuna_trial_params
  - _self_

RETURNS: null

mlflow_tags:
  model_tag: RandomForestRegressor

rf_optuna_trial:
  target_col: ${ml_experiments.target_col_modeling}
  year_col: ${ml_experiments.year_col}
  train_range: ${ml_experiments.train_range}
  val_range: ${ml_experiments.val_range}
  test_range: ${ml_experiments.test_range}
  experiment_name: ${ml_experiments.experiment_prefix}_${now:%Y-%m-%d_%H-%M-%S}
  cv_splits: ${ml_experiments.cv_splits}
  n_trials: 2
  top_n_importances: ${ml_experiments.top_n_importances}
  permutation_importances_filename: ${ml_experiments.permutation_importances_filename}
  randomforest_importances_filename: ${ml_experiments.randomforest_importances_filename}
  hyperparameters: ${model_params.hyperparameters}
  rfr_options:
    bootstrap: true
    oob_score: true
  n_jobs_study: 2
  n_jobs_cv: 1
  n_jobs_final_model: 1
  random_state: ${ml_experiments.rng_seed}
  rfr_mlflow_tags: ${..mlflow_tags}
