# configs/transformations/ridge_optuna_trial.yaml
defaults:
  - base
  - /model_params: ridge_optuna_trial_params
  - _self_

RETURNS: null

ridge_optuna_trial:
  target_col: ${ml_experiments.target_col_modeling}
  year_col: ${ml_experiments.year_col}
  train_range: ${ml_experiments.train_range}
  val_range: ${ml_experiments.val_range}
  test_range: ${ml_experiments.test_range}
  experiment_name: ${ml_experiments.experiment_prefix}_${now:%Y-%m-%d_%H-%M-%S}
  cv_splits: ${ml_experiments.cv_splits}
  n_trials: 10
  top_n_importances: ${ml_experiments.top_n_importances}
  permutation_importances_filename: ${ml_experiments.permutation_importances_filename}
  hyperparameters: ${model_params.hyperparameters}
  n_jobs_study: 5
  n_jobs_cv: 1
  random_state: ${ml_experiments.rng_seed}
