name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-environment.yml
          cache-downloads: true
          cache-environment: true
          environment-name: ci

      - uses: pre-commit/action@v3.0.0

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt

      - name: Cache DVC data
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: dvc-${{ runner.os }}-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            dvc-${{ runner.os }}-

      - name: Pull data/params
        run: dvc pull --verbose --jobs 4

      - name: Flake8
        run: flake8 .

      - name: Pytest + coverage
        run: pytest -q --cov=src --cov-report=xml

      - uses: codecov/codecov-action@v4
        with:
          files: coverage.xml

      - name: Upload MLflow artefacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns
          retention-days: 5

  gpu-pipeline:
    needs: lint-test
    runs-on: self-hosted-gpu
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-environment.yml
          cache-downloads: true
          cache-environment: true
          environment-name: ci

      - uses: iterative/setup-dvc@v1

      - name: Assume AWS role via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GithubOIDCRole
          aws-region: eu-central-1

      - name: Reproduce DVC pipeline
        run: dvc repro --pull -P

      - name: Push artefacts to S3
        run: |
          dvc push --verbose --jobs 4
          aws s3 sync mlruns s3://bucket/mlruns --delete

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            data/**
            models/**
            logs/**
